CREATE USER IF NOT EXISTS 'ohm'@'%' IDENTIFIED BY '2001Serenity';
GRANT ALL PRIVILEGES ON *.* TO 'ohm'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '2001Serenity' WITH GRANT OPTION;
FLUSH PRIVILEGES;
